// Generated by ReScript, PLEASE EDIT WITH CARE


var count = {
  contents: 0
};

var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var countText = document.getElementById("count");

function renderCountText(param) {
  var count$1 = count.contents;
  var className = count$1 > 0 ? "count-positive" : (
      count$1 < 0 ? "count-negative" : "count-zero"
    );
  var numberName = count$1 === 0 ? "Zero" : String(count$1);
  countText.innerText = "Count is " + numberName;
  countText.classList = "count " + className;
  
}

function handleUpdateCount(step) {
  count.contents = count.contents + step | 0;
  return renderCountText(undefined);
}

plusButton.addEventListener("click", (function (param) {
        return handleUpdateCount(1);
      }));

minusButton.addEventListener("click", (function (param) {
        return handleUpdateCount(-1);
      }));

export {
  count ,
  plusButton ,
  minusButton ,
  countText ,
  renderCountText ,
  handleUpdateCount ,
  
}
/* plusButton Not a pure module */
